export const btnAddNew = "button[data-testid='buttonAddNew']"
export const btnCVs = "[data-testid='dashboardCvs']"
export const btnCoverLetter = "[data-testid='dashboardCoverLetter']"
export const btnDashboard = "[data-testid='headerDashboard']"
export const btnCompany = "[data-testid='headerCompany']"
export const btnApply = "[data-testid='headerApply']"
export const btnAccount = "[data-testid='headerAccount']"
export const btnLogout = "[data-testid='headerLogout']"
export const cvTemplateList = "[data-testid='listTemplate'] > div"