export const btnLogin = "button[value='signin']"
export const btnSignup = "button[value='signup']"
export const btnDashboard = "a[href='/dashboard']"
export const btnCreateMyCV = "button[data-testid='btnCreateResume']"
export const lnkAbout = "a[href='/about']"
export const lnkContactUs = "a[href='/contact']"