export const txtEmail = "[data-testid='formSignInEmail']"
export const txtPassword = "[data-testid='formSignInPassword']"
export const chbx_rememberMe = "[data-testid='remember']"
export const lnk_forgotPassword = "[data-testid='forgetPassword']"
export const lnk_createAccount = "[data-testid='btnCreateAccount']"
export const btnLogin = "[data-testid='formSignInButton']"
export const btnLoginWithGoogle = "[data-testid='buttonSignupGoogle']"